@startuml

participant Core
participant HMI

HMI -> Core : AppServiceActivation\n(serviceID: "providerID", \nactivate: true \nsetAsDefault: true)

Core -> Core : SetDefaultService("providerID")

Core -> HMI : AppServiceActivation\n("providerID", true, true)
@enduml
