@startuml GetAppServiceData_HMI_ASP
participant HMIProvider
participant Core
participant MobileConsumer

HMIProvider -> Core: AppService.PublishAppService(MEDIA)
Core --> HMIProvider: AppService.PublishAppService Response
MobileConsumer -> Core: GetAppServiceData(MEDIA)
Core -> HMIProvider: AppService.GetAppServiceData(MEDIA)
HMIProvider --> Core: AppService.GetAppServiceData Response
Core --> MobileConsumer: GetAppServiceData Response

@enduml