@startuml GetAppServiceData_HMI_ASP
participant HMIProvider
participant Core
participant MobileConsumer

note left of HMIProvider: HMI has published a\nMEDIA app service

MobileConsumer -> Core: GetAppServiceData(MEDIA)
Core -> Core : Increase RPC Timeout
Core -> HMIProvider: AppService.GetAppServiceData(MEDIA)
HMIProvider --> Core: AppService.GetAppServiceData Response
Core --> MobileConsumer: GetAppServiceData Response

@enduml