@startuml SubscribeWayPoints
participant SDL
participant HMI

SDL -> HMI: Navigation.SubscribeWayPoints()
HMI --> SDL: Navigation.SubscribeWayPoints(SUCCESS)
note right of HMI: Waypoint data has changed
HMI -> SDL: Navigation.OnWayPointChange(waypoints)
@enduml