@startuml OnSystemCapabilityUpdated_PUBLISHED
participant Mobile
participant Core
participant HMI

Mobile -> Core : PublishAppServiceRequest
Core -> Core : SystemCapability:\nSubscribeTo\n(APP_SERVICES)
Core ->> Mobile : OnSystemCapabilityUpdated\n(APP_SERVICES, PUBLISHED)
Core ->> HMI : BasicCommunication\n.OnSystemCapabilityUpdated\n(APP_SERVICES, PUBLISHED)
Core --> Mobile : PublishAppServiceResponse

@enduml
