@startuml OnSystemCapabilityUpdated_REMOVED

participant Mobile
participant Core
participant AppServiceManager
participant HMI

note left of Mobile: Mobile app has \nmultiple published \napp services

Mobile -> Core : Disconnect
Core -> Core : UnregisterApplication
Core -> AppServiceManager : UnpublishServices(app_id)

loop For Every Published Service On Device
  AppServiceManager -> Core :BroadcastCapabilityUpdate
  Core ->> Mobile : OnSystemCapabilityUpdated\n(APP_SERVICES, REMOVED)
  Core ->> HMI : BasicCommunication.OnSystemCapabilityUpdated\n(APP_SERVICES, REMOVED)
end
@enduml
