@startuml
/'
Source file for sequence diagram
More information at https://plantuml.com/ 
'/

Participant "App" as A
Participant "SDL" as SDL
Participant "HMI" as HMI

A -> SDL: StartService(serviceType:Video, streamingParams)
SDL -> HMI: Navigation.SetVideoConfig(config: streamingParams)
HMI -> SDL: Navigation.SetVideoConfig(SUCCESS)
SDL -> A: StartServiceACK(streamingParams)
SDL -> HMI: Navigation.StartStream(url: http://127.0.0.1:5050)
HMI -> SDL: Navigation.StartStream(SUCCESS)

@enduml