@startuml OnAppServiceData_HMI_ASC
participant HMIConsumer
participant Core
participant MobileProvider

note right of MobileProvider: Mobile app has\npublished a\nMEDIA app service

HMIConsumer -> Core: AppService.GetAppServiceData(MEDIA,subscribe=true)
Core -> MobileProvider: GetAppServiceData(MEDIA,subscribe=true)
MobileProvider --> Core: GetAppServiceData Response
Core --> HMIConsumer: AppService.GetAppServiceData Response
MobileProvider -> MobileProvider: Update service data
MobileProvider ->> Core: OnAppServiceData Notification
Core ->> HMIConsumer: AppService.OnAppServiceData Notification

@enduml