@startuml

skinparam ParticipantPadding 36
skinparam defaultFontSize 10

participant AppConsumer
participant AppProvider
participant Core
participant HMI

AppConsumer -> Core : PerformAppServiceInteraction\n(requestServiceActive:true)
Core -> Core : Increase RPC Timeout
opt Consumer is not in foreground
  Core -> HMI : AS.GetActiveServiceConsent\n("providerID")
  HMI -> HMI : Prompt user to \nactivate service
  HMI --> Core : AS.GetActiveServiceConsent\n(true)
end
Core -> Core : ActivateAppService("providerID")
Core -> AppProvider : PerformAppServiceInteraction()
AppProvider --> Core : PerformAppServiceInteraction\n(serviceSpecificResult:"result", SUCCESS)

Core --> AppConsumer : PerformAppServiceInteraction\n("result", SUCCESS)
@enduml
